apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-server-conf
data:
  nginx.conf: |
        worker_rlimit_nofile 8192;
        events {
          worker_connections  4096;
        }
        http {
            server {
                listen      8080;
                listen [::]:8080;
                root /www/data;
                location / {
                }
            }
        }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-server
spec:
  selector:
    matchLabels:
      app: nginx-server
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-server
    spec:
      initContainers:
      - name: init-files
        image: busybox
        command: ["/bin/sh","-c"]
        args: [" wget https://cyberarmor-network-tests-files.s3.eu-central-1.amazonaws.com/random-1b.txt -P /www/data; wget https://cyberarmor-network-tests-files.s3.eu-central-1.amazonaws.com/random-1kb.txt -P /www/data; wget https://cyberarmor-network-tests-files.s3.eu-central-1.amazonaws.com/random-1mb.txt -P /www/data; wget https://cyberarmor-network-tests-files.s3.eu-central-1.amazonaws.com/random-10mb.txt -P /www/data; wget https://cyberarmor-network-tests-files.s3.eu-central-1.amazonaws.com/random-100mb.txt -P /www/data "]
        volumeMounts:
        - mountPath: /www/data
          name: files-volume
      containers:
      - name: nginx-server
        image: nginx:1.14.2
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /etc/nginx # mount nginx-conf volumn to /etc/nginx
          readOnly: true
          name: nginx-server-conf
        - mountPath: /www/data
          name: files-volume
      volumes:
      - name: nginx-server-conf
        configMap:
          name: nginx-server-conf # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf
      - name: files-volume # place file for download on /www/data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: server-uut
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: nginx-server
